# Generated by Django 4.0 on 2022-01-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communicator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
